{% set name = "aws-parallelcluster" %}
{% set version = "2.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 60d96a5ea4dca4816ceffc4546549743abd1f6207c62f016c9c348adc64b2ec0

build:
  number: 0
  entry_points:
    - pcluster = pcluster.cli:main
    - awsbqueues = awsbatch.awsbqueues:main
    - awsbhosts = awsbatch.awsbhosts:main
    - awsbstat = awsbatch.awsbstat:main
    - awsbkill = awsbatch.awsbkill:main
    - awsbsub = awsbatch.awsbsub:main
    - awsbout = awsbatch.awsbout:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - python
    - setuptools
    - boto3 >=1.16.14
    - tabulate >=0.8.6,<=0.8.7
    - future >=0.18.2
    - pyyaml >=5.3.1
    - configparser >=4.0.2  # [py2k]
    - jinja2 >=2.11.0

test:
  imports:
    - awsbatch
    - pcluster
  commands:
    - pcluster --help
    - awsbqueues --help
    - awsbhosts --help
    - awsbstat --help
    - awsbkill --help
    - awsbsub --help
    - awsbout --help

about:
  home: https://github.com/aws/aws-parallelcluster
  license: Apache-2.0
  license_family: APACHE
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.txt
  summary: AWS ParallelCluster is an AWS supported Open Source cluster management tool to deploy and manage HPC clusters in the AWS cloud.
  doc_url: https://aws-parallelcluster.readthedocs.io/en/v{{ version }}/
  dev_url: https://github.com/aws/aws-parallelcluster

extra:
  recipe-maintainers:
    - notestaff
    - sean-smith
    - lukeseawalker
    - demartinofra
    - tilne
    - rexcsn
    - enrico-usai
    - ddeidda
    - chenwany
    - charlesg3
    - yuleiwan
    - hanwen-pcluste
