{% set name = "aws-parallelcluster" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4eaa6b075c7e03bef53a943e8c7ca72c79ae6a8e5d163d0892f66dc50d21d417

build:
  number: 0
  entry_points:
    - pcluster = pcluster.cli.entrypoint:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - python
    - setuptools
    - boto3>=1.16.14
    - tabulate~=0.8
    - pyyaml>=5.3.1
    - jinja2>=2.11.0
    - connexion==2.7.0
    - flask~=2.0
    - jmespath~=0.10
    - werkzeug~=2.0
    - marshmallow~=3.10

test:
  imports:
    - pcluster
  commands:
    - pcluster --help

about:
  home: https://github.com/aws/aws-parallelcluster
  license: Apache-2.0
  license_family: APACHE
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.txt
  summary: AWS ParallelCluster is an AWS supported Open Source cluster management tool to deploy and manage HPC clusters in the AWS cloud.
  doc_url: https://aws-parallelcluster.readthedocs.io/en/v{{ version }}/
  dev_url: https://github.com/aws/aws-parallelcluster

extra:
  recipe-maintainers:
    - notestaff
    - sean-smith
    - lukeseawalker
    - demartinofra
    - tilne
    - enrico-usai
    - chenwany
    - charlesg3
    - yuleiwan
    - hanwen-pcluste
