{% set name = "aws-parallelcluster" %}
{% set version = "2.5.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 4fd6e14583f8cf81f9e4aa1d6188e3708d3d14e6ae252de0a94caaf58be76303

build:
  number: 0
  entry_points:
    - pcluster = pcluster.cli:main
    - awsbqueues = awsbatch.awsbqueues:main
    - awsbhosts = awsbatch.awsbhosts:main
    - awsbstat = awsbatch.awsbstat:main
    - awsbkill = awsbatch.awsbkill:main
    - awsbsub = awsbatch.awsbsub:main
    - awsbout = awsbatch.awsbout:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python
    - setuptools
    - boto3 >=1.10.15
    - future >=0.16.0,<=0.18.2
    - tabulate >=0.8.2,<=0.8.3
    - configparser >=3.5.0,<=3.5.3  # [py2k]
    - ipaddress >=1.0.22
    - enum34 >=1.1.6
    - PyYAML >=5.1.2

test:
  imports:
    - awsbatch
    - pcluster
  commands:
    - pcluster --help
    - awsbqueues --help
    - awsbhosts --help
    - awsbstat --help
    - awsbkill --help
    - awsbsub --help
    - awsbout --help

about:
  home: "https://github.com/aws/aws-parallelcluster"
  license: "Apache-2.0"
  license_family: "APACHE"
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: "AWS ParallelCluster is an AWS supported Open Source cluster management tool to deploy and manage HPC clusters in the AWS cloud."
  doc_url: "https://aws-parallelcluster.readthedocs.io/en/v{{ version }}/"
  dev_url: "https://github.com/aws/aws-parallelcluster"

extra:
  recipe-maintainers:
    - notestaff
    - sean-smith
    - lukeseawalker
    - demartinofra
