{% set name = "aws-parallelcluster" %}
{% set version = "3.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aws-parallelcluster-{{ version }}.tar.gz
  sha256: cabb2ae83a4d127f9507344458f3028bad30e682b54bb94ac3f5c7174ca43eed

build:
  entry_points:
    - pcluster = pcluster.cli.entrypoint:main
    - pcluster3-config-converter = pcluster3_config_converter.pcluster3_config_converter:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python-jsii ==1.85.0
    - python >={{ python_min }}
    - setuptools
    - boto3 >=1.16.14
    - tabulate >=0.8.8,<=0.8.10
    - pyyaml >=5.3.1,!=5.4
    - jinja2 >=3.0,<4.dev0
    - marshmallow >=3.10,<4.dev0
    - aws-cdk.core >=1.164,<2.dev0
    - aws-cdk.aws-batch >=1.164,<2.dev0
    - aws-cdk.aws-cloudwatch >=1.164,<2.dev0
    - aws-cdk.aws-codebuild >=1.164,<2.dev0
    - aws-cdk.aws-dynamodb >=1.164,<2.dev0
    - aws-cdk.aws-ec2 >=1.164,<2.dev0
    - aws-cdk.aws-efs >=1.164,<2.dev0
    - aws-cdk.aws-events >=1.164,<2.dev0
    - aws-cdk.aws-fsx >=1.164,<2.dev0
    - aws-cdk.aws-imagebuilder >=1.164,<2.dev0
    - aws-cdk.aws-iam >=1.164,<2.dev0
    - aws-cdk.aws-lambda >=1.164,<2.dev0
    - aws-cdk.aws-logs >=1.164,<2.dev0
    - aws-cdk.aws-route53 >=1.164,<2.dev0
    - aws-cdk.aws-ssm >=1.164,<2.dev0
    - aws-cdk.aws-sqs >=1.164,<2.dev0
    - aws-cdk.aws-cloudformation >=1.164,<2.dev0
    - werkzeug >=2.0,<3.dev0
    - connexion >=2.13.0,<2.14.dev0
    - flask >=2.2.5,<2.3
    - jmespath >=0.10,<1.dev0

test:
  imports:
    - pcluster
    - pcluster3_config_converter
  commands:
    - pip check
    - pcluster --help
    - pcluster3-config-converter --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aws/aws-parallelcluster
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: AWS ParallelCluster is an AWS supported Open Source cluster management tool to deploy and manage HPC clusters in the AWS cloud.
  doc_url: https://docs.aws.amazon.com/parallelcluster
  dev_url: https://github.com/aws/aws-parallelcluster

extra:
  recipe-maintainers:
    - notestaff
    - lukeseawalker
    - demartinofra
    - enrico-usai
    - charlesg3
    - hanwen-pcluste
    - gmarciani
    - dreambeyondorange
    - jdeamicis
    - himani2411
    - hgreebe
